name: Parse and send articles to channel

on:
  schedule:
    - cron: "0 8 * * *"

jobs:
  parse-and-send-task:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонирование репозитория
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: true

      # 2. Убедимся, что все субмодули обновлены
      - name: Ensure submodules are updated
        run: |
          git submodule update --init --recursive

      # 3. Установка Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 4. Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Запуск Selenium-скрипта
      - name: Run Selenium script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        run: python parse_and_send.py


      # 6. Проверить, добавить ID статей и коммитить изменения
      - name: Commit article IDs
        run: |
          # Проверка на наличие изменений в файле с ID
          git config --global user.email "ramil2911912@gmail.com"
          git config --global user.name "GitHub Actions"
          
          # Добавление и коммит изменений в файл sent_articles.txt
          git add sent_articles.txt
          git commit -m "Update sent article IDs"
          git push
